name: moxlib
description: A collection of code for sharing between various moxxy libraries. Not intended for outside use.
version: 0.2.0
homepage: https://codeberg.org/moxxy/moxlib
publish_to: https://git.polynom.me/api/packages/Moxxy/pub

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  logging: ^1.0.2
  meta: ^1.7.0
  synchronized: ^3.0.0
  uuid: ^3.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.20.1
  very_good_analysis: ^5.0.0
